# Generated by Django 2.0.3 on 2020-11-23 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gem', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shouyang',
            name='money',
            field=models.CharField(default=-1, max_length=10),
        ),
    ]
