# Generated by Django 2.0.3 on 2020-11-23 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gem', '0003_auto_20201123_1453'),
    ]

    operations = [
        migrations.CreateModel(
            name='totalCalculate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('a1', models.IntegerField(default=0)),
                ('a2', models.IntegerField(default=0)),
                ('a3', models.IntegerField(default=0)),
                ('a4', models.IntegerField(default=0)),
                ('a5', models.IntegerField(default=0)),
                ('a6', models.IntegerField(default=0)),
                ('a7', models.IntegerField(default=0)),
            ],
        ),
    ]
