# Generated by Django 2.0.3 on 2020-12-06 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gem', '0004_totalcalculate'),
    ]

    operations = [
        migrations.AddField(
            model_name='yangpin',
            name='jcy',
            field=models.CharField(default='未分配', max_length=20),
        ),
    ]
