# Generated by Django 2.0.3 on 2020-12-06 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gem', '0005_yangpin_jcy'),
    ]

    operations = [
        migrations.AddField(
            model_name='yangpin',
            name='certificate',
            field=models.CharField(default='未生成证书', max_length=20),
        ),
    ]
