# Generated by Django 2.0.3 on 2020-12-06 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gem', '0006_yangpin_certificate'),
    ]

    operations = [
        migrations.AddField(
            model_name='yangpin',
            name='name',
            field=models.CharField(default='--', max_length=20),
        ),
    ]
