# Generated by Django 2.0.3 on 2020-12-19 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gem', '0008_vip'),
    ]

    operations = [
        migrations.CreateModel(
            name='CHECK_PATH',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PicUrl', models.CharField(max_length=120)),
                ('ChechMan', models.CharField(max_length=20)),
                ('TaskAttri', models.CharField(max_length=6)),
                ('Code', models.CharField(max_length=4)),
                ('StoneId', models.CharField(max_length=10)),
                ('Result', models.CharField(max_length=10)),
                ('Appearance', models.IntegerField()),
                ('Massive', models.FloatField()),
                ('Density', models.FloatField()),
                ('Refraction', models.FloatField()),
                ('LightFigure', models.IntegerField()),
                ('Detail', models.CharField(max_length=150)),
                ('ORD', models.CharField(max_length=50)),
                ('Uid', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='MEMBER_INFO',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('MemberName', models.CharField(max_length=10)),
                ('MemberTel', models.CharField(max_length=11)),
                ('MemberType', models.CharField(max_length=10)),
                ('Represent', models.CharField(max_length=50)),
                ('BookId', models.CharField(max_length=20)),
                ('PostId', models.CharField(max_length=6)),
                ('MenberComp', models.CharField(max_length=150)),
                ('MemCompAddr', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='ORIGINAL_CHECK',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Uid', models.CharField(max_length=10)),
                ('Tel', models.CharField(max_length=11)),
                ('Atti', models.CharField(max_length=4)),
                ('Order', models.CharField(max_length=6)),
                ('SendId', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='ORIGINAL_INNERINFO',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Total', models.IntegerField()),
                ('finishTime', models.DateField()),
                ('Pick', models.CharField(max_length=20)),
                ('Cost', models.FloatField()),
                ('pickTime', models.DateField()),
                ('IsPay', models.BooleanField()),
                ('Uid', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='ORIGINAL_SENDER',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Scomp', models.CharField(max_length=70)),
                ('Sper', models.CharField(max_length=20)),
                ('Stel', models.CharField(max_length=11)),
                ('Spost', models.CharField(max_length=6)),
                ('SendId', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='TASK_MANAGE',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('StoneId', models.CharField(max_length=10)),
                ('Demand', models.CharField(default='无', max_length=200)),
                ('Condition', models.CharField(default='无', max_length=200)),
                ('Dived', models.CharField(max_length=20)),
                ('Book', models.CharField(max_length=20)),
            ],
        ),
    ]
