# Generated by Django 2.0.3 on 2020-12-19 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gem', '0009_check_path_member_info_original_check_original_innerinfo_original_sender_task_manage'),
    ]

    operations = [
        migrations.CreateModel(
            name='基本设置',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('单页表格长度上限', models.CharField(default='未填写', max_length=20)),
                ('站点编号', models.CharField(default='未填写', max_length=20)),
                ('当前编号', models.CharField(default='未填写', max_length=20)),
                ('默认检测批号', models.CharField(default='未填写', max_length=20)),
                ('电子秤默认串口', models.CharField(default='未填写', max_length=20)),
                ('电子秤显示精度', models.CharField(default='未填写', max_length=20)),
                ('电子秤默认波特率', models.CharField(default='未填写', max_length=20)),
                ('默认分页长度', models.CharField(default='未填写', max_length=20)),
                ('默认证书存储路径', models.CharField(default='未填写', max_length=20)),
                ('默认报表存储路径', models.CharField(default='未填写', max_length=20)),
            ],
        ),
    ]
