# Generated by Django 2.0.3 on 2020-12-19 06:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gem', '0010_基本设置'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='基本设置',
            new_name='a基本设置',
        ),
    ]
